version: '3.4'

services:
  finalproject:
    container_name: qpafinalproject
    build:
      dockerfile: ./Dockerfile
    depends_on:
        - db    
  db:
    container_name: postgres
    image: postgres:14-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_1_db

volumes:
  postgres_data: